engines:
  tailor:
    enabled: true
  fixme:
    enabled: true
  swiftlint:
    enabled: true
ratings:
  paths:
  - "**.swift"
exclude_paths:
- "docs/"
- "JumpingUITextField/JumpingUITextFieldDemo/"
- "JumpingUITextField/JumpingUITextFieldTests/"
